on: [push, pull_request]
name: ShellCheck

permissions:
  contents: read

jobs:
  konstruktoidShellCheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Konstruktoid ShellCheck
        uses: ./action-shellcheck
